language: php
php:
  - 5.4

before_script:
  - rm -rf !(composer.json|.travis.yml)
  - sed -i '2,3d' composer.json
  - composer require t3board/board:*
  - composer install --dev
  - sed -i '/Subroutes from the Welcome package/,+12d' Configuration/Routes.yaml

script:
  - phpunit -c Packages/Application/T3Board.Board/Tests/Unit.xml

