language: php
php:
  - 5.4

before_script:
  - rm -rf !(composer.json.dist|.travis.yml)
  - mv composer.json.dist composer.json
  - composer install --dev

script:
  - phpunit -c Packages/Application/T3Board.Board/Tests/Unit.xml

